apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
#  labels:
#    app: seldon
  name: dummy-demo-rep-int
  namespace: kubeflow-user-example-com
spec:
#  annotations:
#    seldon.io/istio-gateway: mesh
  name: dummy-demo-int
  predictors:
    - componentSpecs:
      - spec:
          containers:
          - image: noheroes/mlserver-rep-scoring-int:latest
            name: classifier
      graph:
        children: []
        endpoint:
          type: GRPC
        name: classifier
        type: MODEL
#      labels:
#        sidecar.istio.io/inject: "true"
      name: example
      replicas: 1
